strings: strings.c
	cc -o strings strings.c -lcs50
string-length: string-length.c
	cc -o string-length string-length.c -lcs50
string-length2: string-length2.c
	cc -o string-length2 string-length2.c -lcs50
lowercase: lowercase.c
	cc -o lowercase lowercase.c -lcs50
uppercase: uppercase.c
	cc -o uppercase uppercase.c -lcs50
