array: array.c
	cc -o array array.c -lcs50
agree: agree.c
	cc -o agree agree.c -lcs50
compare: compare.c
	cc -o compare compare.c -lcs50``
meow: meow.c
	cc -o meow meow.c -lcs50
mario: mario.c
	cc -o mario mario.c -lcs50
calculator: calculator.c
	cc -o calculator calculator.c -lcs50